'use client';

import Image from 'next/image';
import { useState } from 'react';

const whatsappNumber = '14244405544';
const brands = [
  { name: 'BMW', icon: '/icons/bmw.svg' },
  { name: 'Mercedes-Benz', icon: '/icons/mercedes.svg' },
  { name: 'Toyota', icon: '/icons/toyota.svg' },
  { name: 'Volkswagen', icon: '/icons/volkswagen.svg' },
  { name: 'Kia', icon: '/icons/kia.svg' },
  { name: 'Chevrolet', icon: '/icons/chevrolet.svg' },
  { name: 'Nissan', icon: '/icons/nissan.svg' },
] as const;

const copy = {
  en: { top: 'Mobile key lab · Los Angeles', open: 'Open daily · 7:00 AM–10:00 PM', nav1: 'Services', nav2: 'How it works', nav3: 'Why LAX Keys', wa: 'WhatsApp us', eyebrow: 'Car keys, without the dealership', titleA: 'Locked out?', titleB: 'Keep moving.', hero: 'Dealership-grade car keys cut and programmed at your location. Fast, direct and built for the moment you need help most.', start: 'Start on WhatsApp', how: 'See how it works', proof: 'Same-day mobile service', serving: 'Serving drivers across Los Angeles', imageLabel: '01 / ON THE ROAD', imageTitle: 'Your key. Your location.', keys: 'KEYS FROM', starting: 'starting price', arrival: 'AVERAGE ARRIVAL', trusted: 'Trusted technology for', whyKicker: 'Why drivers call LAX Keys', whyTitleA: 'The smarter way back', whyTitleB: 'on the road.', whyLead: 'A locked car should not turn into a tow truck, a two-day wait or a surprise dealer bill.', whyBody: 'Our mobile lab comes to you with the tools to cut, program and test your key on-site — with a clear quote before dispatch.', quote: 'Get a quote on WhatsApp', stat1: 'Daily service hours', stat2: 'Minutes, depending on traffic', stat3: 'Key workmanship warranty', stat4: 'Keys starting from', solve: 'What we solve', solveA: 'From “I lost my key”', solveB: '“I’m on my way.”', solveBody: 'One specialist. One mobile lab. A clean solution at your location.', solveButton: 'Tell us what happened', services: [['01', 'Lost key replacement', 'Cut and program a new key at your location.'], ['02', 'Smart key programming', 'Proximity, keyless entry, transponder and ECU pairing.'], ['03', 'Rapid lockout help', 'Get back inside without damaging your vehicle.']], processKicker: 'A better kind of emergency service', processA: 'Three steps.', processB: 'No runaround.', processBody: 'Send us your vehicle make, model and location. We will confirm the right solution and price before we head your way.', steps: [['Message us', 'Tell us the make, model and what happened.'], ['Get a clear quote', 'Know the price before dispatch. No surprise charges.'], ['Get back in motion', 'We cut, program and test the key at your location.']], promise: 'The LAX Keys promise', promiseA: 'No tow.', promiseB: 'No dealer.', promiseC: 'No surprises.', promiseBody: 'Get dealership-grade automotive key service brought directly to you, backed by a 3-month warranty on the key.', pills: ['✓ Quote before dispatch', '✓ Mobile service', '✓ 3-month warranty'], promiseButton: 'WhatsApp LAX Keys', dispatch: 'Dispatch', coverage: 'Coverage', mobile: 'Mobile key lab', footerTag: 'Bypassing the tow truck since 2020.', footerLine: 'Keys cut & programmed roadside', aria: 'Message LAX Keys on WhatsApp' },
  es: { top: 'Laboratorio móvil de llaves · Los Ángeles', open: 'Horario: 7:00 a. m.–10:00 p. m.', nav1: 'Servicios', nav2: 'Cómo funciona', nav3: 'Por qué LAX Keys', wa: 'Escríbenos', eyebrow: 'Llaves de auto, sin ir al dealer', titleA: '¿Te quedaste fuera?', titleB: 'Sigue avanzando.', hero: 'Llaves de auto con tecnología de dealer, cortadas y programadas donde estés. Rápido, directo y listo cuando más lo necesitas.', start: 'Empezar por WhatsApp', how: 'Ver cómo funciona', proof: 'Servicio móvil el mismo día', serving: 'Atendemos conductores en Los Ángeles', imageLabel: '01 / EN CAMINO', imageTitle: 'Tu llave. Donde estés.', keys: 'LLAVES DESDE', starting: 'precio inicial', arrival: 'LLEGADA PROMEDIO', trusted: 'Tecnología para las marcas', whyKicker: 'Por qué llaman a LAX Keys', whyTitleA: 'La forma inteligente', whyTitleB: 'de volver al camino.', whyLead: 'Un auto cerrado no debería convertirse en grúa, dos días de espera o una cuenta sorpresa del dealer.', whyBody: 'Nuestro laboratorio móvil llega con las herramientas para cortar, programar y probar tu llave ahí mismo — con cotización clara antes de salir.', quote: 'Cotiza por WhatsApp', stat1: 'Horario de atención', stat2: 'Minutos, según el tráfico', stat3: 'Garantía de trabajo en llave', stat4: 'Llaves desde', solve: 'Lo que resolvemos', solveA: 'De “perdí mi llave”', solveB: 'a “ya voy en camino.”', solveBody: 'Un especialista. Un laboratorio móvil. Una solución limpia donde estés.', solveButton: 'Cuéntanos qué pasó', services: [['01', 'Reemplazo de llave perdida', 'Cortamos y programamos una llave nueva donde estés.'], ['02', 'Programación de smart keys', 'Proximidad, entrada sin llave, transponder y ECU.'], ['03', 'Apertura rápida del auto', 'Vuelve a entrar sin dañar tu vehículo.']], processKicker: 'Una mejor forma de resolver emergencias', processA: 'Tres pasos.', processB: 'Sin vueltas.', processBody: 'Mándanos la marca, modelo y ubicación. Confirmamos la solución y el precio antes de dirigirnos contigo.', steps: [['Escríbenos', 'Dinos la marca, modelo y qué sucedió.'], ['Recibe una cotización clara', 'Conoce el precio antes de salir. Sin cargos sorpresa.'], ['Vuelve al camino', 'Cortamos, programamos y probamos tu llave ahí mismo.']], promise: 'La promesa LAX Keys', promiseA: 'Sin grúa.', promiseB: 'Sin dealer.', promiseC: 'Sin sorpresas.', promiseBody: 'Servicio de llaves automotrices con tecnología de dealer, directo donde estás y con garantía de 3 meses sobre la llave.', pills: ['✓ Cotización antes de salir', '✓ Servicio móvil', '✓ Garantía de 3 meses'], promiseButton: 'WhatsApp LAX Keys', dispatch: 'Atención', coverage: 'Cobertura', mobile: 'Laboratorio móvil de llaves', footerTag: 'Evitando la grúa desde 2020.', footerLine: 'Llaves cortadas y programadas en camino', aria: 'Escribir a LAX Keys por WhatsApp' },
} as const;

export default function Home() {
  const [lang, setLang] = useState<'en' | 'es'>('es');
  const t = copy[lang];
  const whatsappLink = `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(lang === 'es' ? 'Hola LAX Keys, necesito ayuda con la llave de mi auto.' : 'Hi LAX Keys, I need help with my car key.')}`;
  return <main lang={lang}>
    <style>{`@keyframes pulseGlow{0%,100%{opacity:.45;transform:scale(.96)}50%{opacity:.8;transform:scale(1.04)}}@keyframes floatCard{0%,100%{transform:rotate(2deg) translateY(0)}50%{transform:rotate(1deg) translateY(-8px)}}@keyframes drift{0%{transform:rotate(-28deg) translate(0,0)}50%{transform:rotate(-24deg) translate(12px,-5px)}100%{transform:rotate(-28deg) translate(0,0)}}@keyframes whatsappPulse{0%,100%{box-shadow:0 10px 28px #15803d66,0 0 0 0 #16a34a55}50%{box-shadow:0 13px 32px #15803d88,0 0 0 10px #16a34a00}}.visual-glow{animation:pulseGlow 5s ease-in-out infinite}.image-card{animation:floatCard 6s ease-in-out infinite}.orbit-one{animation:drift 8s ease-in-out infinite}.image-card:after{content:'7–10';position:absolute;right:-18px;bottom:22%;display:grid;place-items:center;width:54px;height:54px;border-radius:50%;background:#171718;color:#f3d89a;font:800 12px Arial;letter-spacing:.04em;box-shadow:0 12px 24px #17171840;transform:rotate(8deg)}.button-primary{box-shadow:0 10px 24px #bd2b2138}.button-primary:hover{box-shadow:0 14px 30px #bd2b2155}.brand-name{transition:color .2s,transform .2s}.brand-name:hover{color:#bd2b21;transform:translateY(-2px)}.whatsapp-float-attention{animation:whatsappPulse 2.4s ease-in-out infinite}.whatsapp-float-attention:hover{transform:translateY(-4px) scale(1.04)}@media(prefers-reduced-motion:reduce){.visual-glow,.image-card,.orbit-one,.whatsapp-float-attention{animation:none}}`}</style>
    <div className="topbar"><span><i className="status-dot" /> {t.top}</span><span>{t.open}</span></div>
    <nav className="nav shell"><a className="brand" href="#top" aria-label="LAX Keys home"><Image className="brand-logo" src="/images/lax-keys-logo.jpeg" alt="LAX Keys" width={160} height={160} priority /><span className="sr-only">LAX Keys</span></a><div className="nav-links nav-links-ribbon"><a href="#services">{t.nav1}</a><a href="#how-it-works">{t.nav2}</a><a href="#why-us">{t.nav3}</a></div><div style={{display:'flex',alignItems:'center',gap:16}}><div className="nav-links" aria-label="Language selector" style={{gap:5}}><button style={{padding:0,border:0,background:'transparent',cursor:'pointer',fontWeight:800,color:lang === 'es' ? '#bd2b21' : '#aaa39a'}} onClick={() => setLang('es')}>ES</button><span>/</span><button style={{padding:0,border:0,background:'transparent',cursor:'pointer',fontWeight:800,color:lang === 'en' ? '#bd2b21' : '#aaa39a'}} onClick={() => setLang('en')}>EN</button></div><a className="button button-small button-dark" href={whatsappLink}>{t.wa} <span>↗</span></a></div></nav>
    <section className="hero shell" id="top"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-line" /> {t.eyebrow}</p><h1>{t.titleA}<br /><em>{t.titleB}</em></h1><p className="hero-text">{t.hero}</p><div className="hero-actions"><a className="button button-primary" href={whatsappLink}>{t.start} <span>↗</span></a><a className="text-link" href="#how-it-works">{t.how} <span>↓</span></a></div><div className="hero-proof"><div className="avatar-stack" aria-hidden="true"><span>LA</span><span>10</span><span>★</span></div><p><strong>{t.proof}</strong><br />{t.serving}</p></div></div><div className="hero-visual"><div className="visual-glow" /><div className="image-card"><Image src="/images/lax-keys-van-offer.jpeg" alt={lang === 'es' ? 'Van de laboratorio móvil de llaves LAX Keys en Los Ángeles' : 'LAX Keys mobile key lab van in Los Angeles'} width={768} height={1365} priority style={{width:'100%',height:'auto',maxHeight:'620px',objectFit:'contain',background:'#111'}} /><div className="image-caption"><span>{t.imageLabel}</span><strong>{t.imageTitle}</strong></div></div><div className="floating-badge badge-price" style={{top:'-28px',right:'10px'}}><small>{t.keys}</small><strong>$95</strong><span>{t.starting}</span></div><div className="floating-badge badge-time"><span className="badge-icon">◷</span><div><small>{t.arrival}</small><strong>30–40 min</strong></div></div><div className="orbit orbit-one" /><div className="orbit orbit-two" /></div></section>
    <section className="brand-strip"><div className="shell brand-row"><span className="muted-label">{t.trusted}</span><div className="brand-scroll" aria-label={lang === 'es' ? 'Marcas atendidas' : 'Supported vehicle brands'}>{brands.map((brand) => <span className="brand-chip" key={brand.name}><span className="brand-symbol" aria-hidden="true"><Image src={brand.icon} alt="" width={25} height={25} /></span><span className="brand-name">{brand.name}</span></span>)}</div></div></section>
    <section className="brand-showcase" aria-label={lang === 'es' ? 'Marcas que atendemos' : 'Brands we service'}><div className="shell showcase-intro"><span>{lang === 'es' ? 'Una llave para cada camino' : 'One key for every road'}</span><strong>{lang === 'es' ? 'Tecnología para las marcas que manejas.' : 'Technology for the brands you drive.'}</strong></div><div className="brand-marquee"><div className="brand-marquee-track">{[...brands, ...brands].map((brand, index) => <span className="showcase-brand" key={`${brand.name}-${index}`}><span className="showcase-brand-icon" aria-hidden="true"><Image src={brand.icon} alt="" width={34} height={34} /></span>{brand.name}</span>)}</div></div></section>
    <section className="section shell intro-section" id="why-us"><div className="section-kicker">{t.whyKicker}</div><div className="intro-grid"><h2>{t.whyTitleA} <em>{t.whyTitleB}</em></h2><div><p className="lead">{t.whyLead}</p><p>{t.whyBody}</p><a className="arrow-link" href={whatsappLink}>{t.quote} <span>↗</span></a></div></div><div className="stat-grid"><div><strong>7–10</strong><span>{t.stat1}</span></div><div><strong>30–40</strong><span>{t.stat2}</span></div><div><strong>3 mo.</strong><span>{t.stat3}</span></div><div><strong>$95</strong><span>{t.stat4}</span></div></div></section>
    <section className="dark-section" id="services"><div className="shell service-layout"><div><div className="section-kicker light">{t.solve}</div><h2>{t.solveA}<br />{t.solveB}</h2><p className="dark-copy">{t.solveBody}</p><a className="button button-light" href={whatsappLink}>{t.solveButton} <span>↗</span></a></div><div className="service-list">{t.services.map(([number, title, description]) => <div className="service-item" key={number}><span className="service-number">{number}</span><div><h3>{title}</h3><p>{description}</p></div><span className="service-arrow">↗</span></div>)}</div></div></section>
    <section className="section shell process-section" id="how-it-works"><div className="section-kicker">{t.processKicker}</div><div className="process-heading"><h2>{t.processA}<br /><em>{t.processB}</em></h2><p>{t.processBody}</p></div><div className="process-grid">{t.steps.map(([title, body], index) => <div key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{body}</p></div>)}</div></section>
    <section className="offer-section shell"><div className="offer-card"><div><div className="section-kicker">{t.promise}</div><h2>{t.promiseA}<br /><em>{t.promiseB}</em><br />{t.promiseC}</h2></div><div className="offer-details"><p>{t.promiseBody}</p><div className="offer-pills">{t.pills.map((pill) => <span key={pill}>{pill}</span>)}</div><a className="button button-primary" href={whatsappLink}>{t.promiseButton} <span>↗</span></a></div></div></section>
    <footer className="footer"><div className="shell footer-grid"><div><a className="brand footer-brand" href="#top"><Image className="brand-logo footer-logo" src="/images/lax-keys-logo.jpeg" alt="LAX Keys" width={220} height={220} /><span className="sr-only">LAX Keys</span></a><p>{t.footerTag}</p></div><div><span className="footer-label">{t.dispatch}</span><a href={whatsappLink}>{lang === 'es' ? 'WhatsApp 7:00 a. m.–10:00 p. m.' : 'WhatsApp 7:00 AM–10:00 PM'}</a><a href="tel:+14244405544">(424) 440-5544</a></div><div><span className="footer-label">{t.coverage}</span><span>Los Angeles, CA</span><span>{t.mobile}</span></div><div className="footer-legal"><span className="footer-label">Legal</span><a href="#privacy">{lang === 'es' ? 'Aviso de privacidad' : 'Privacy notice'}</a><a href="#terms">{lang === 'es' ? 'Términos de servicio' : 'Terms of service'}</a></div><div className="footer-social"><span className="footer-label">{lang === 'es' ? 'Redes sociales' : 'Social'}</span><a className="social-link" href="https://www.instagram.com/laxkeys/" target="_blank" rel="noreferrer"><span className="social-icon" aria-hidden="true"><Image src="/icons/instagram.svg" alt="" width={18} height={18} /></span>Instagram</a><a className="social-link" href="https://www.facebook.com/gilberto.arteaga.716/" target="_blank" rel="noreferrer"><span className="social-icon" aria-hidden="true"><Image src="/icons/facebook.svg" alt="" width={18} height={18} /></span>Facebook</a><a className="social-link" href="https://www.tiktok.com/@lax.keys1" target="_blank" rel="noreferrer"><span className="social-icon" aria-hidden="true"><Image src="/icons/tiktok.svg" alt="" width={18} height={18} /></span>TikTok</a></div></div><div className="shell footer-bottom"><span>© 2026 LAX KEYS</span><span>{t.footerLine}</span><span>{lang === 'es' ? 'Horario: 7:00 a. m.–10:00 p. m.' : 'Hours: 7:00 AM–10:00 PM'}</span></div></footer>
    <section className="section shell" aria-label={lang === 'es' ? 'Prueba visual de nuestros servicios' : 'Visual proof of our services'}><div className="section-kicker">{lang === 'es' ? 'La diferencia se ve' : 'The difference is visible'}</div><div className="process-heading"><h2>{lang === 'es' ? <>Servicio real.<br /><em>Confianza real.</em></> : <>Real service.<br /><em>Real confidence.</em></>}</h2><p>{lang === 'es' ? 'Desde una emergencia de noche hasta la programación de una llave europea: llevamos la solución hasta tu auto.' : 'From a nighttime emergency to European key programming: we bring the solution to your car.'}</p></div><div className="process-grid"><div style={{padding:0,overflow:'hidden'}}><Image src="/images/night-emergency-dispatch.jpeg" alt={lang === 'es' ? 'Servicio de emergencia nocturna de LAX Keys' : 'LAX Keys nighttime emergency service'} width={1158} height={2048} style={{display:'block',width:'100%',height:'430px',objectFit:'contain'}} /><div style={{padding:'20px 22px 24px'}}><span>01</span><h3>{lang === 'es' ? 'Llegamos cuando importa' : 'We show up when it matters'}</h3></div></div><div style={{padding:0,overflow:'hidden'}}><Image src="/images/european-key-specialist.png" alt={lang === 'es' ? 'Programación de llave BMW por LAX Keys' : 'BMW key programming by LAX Keys'} width={1158} height={2048} style={{display:'block',width:'100%',height:'430px',objectFit:'contain'}} /><div style={{padding:'20px 22px 24px'}}><span>02</span><h3>{lang === 'es' ? 'Precisión europea' : 'European precision'}</h3></div></div><div style={{padding:0,overflow:'hidden'}}><Image src="/images/dealer-price-comparison.jpeg" alt={lang === 'es' ? 'Comparación entre precio del dealer y LAX Keys' : 'Dealer price compared with LAX Keys'} width={1158} height={2048} style={{display:'block',width:'100%',height:'430px',objectFit:'contain'}} /><div style={{padding:'20px 22px 24px'}}><span>03</span><h3>{lang === 'es' ? 'Más inteligente que el dealer' : 'Smarter than the dealer'}</h3></div></div></div></section>
    <a className="whatsapp-float whatsapp-float-attention" href={whatsappLink} aria-label={t.aria} style={{background:'#16a34a',border:'3px solid #fff',padding:'18px 28px',boxShadow:'0 10px 28px #15803d66',fontSize:'15px',minWidth:'205px'}}><span style={{fontSize:'24px',fontWeight:800}}>◉</span> {t.wa} <small style={{fontSize:'10px',opacity:.9,letterSpacing:'.08em'}}>7–10</small></a>
  </main>;
}
